"""Segmentation mask models, encodings, image IO, and interop adapters."""

from __future__ import annotations

from xpkg.segmentation.coco import (
    annotation_to_masks,
    annotations_to_masks,
    coco_rle_to_mask,
    mask_to_coco_annotation,
    mask_to_coco_polygons,
    mask_to_coco_rle,
    read_coco_annotations,
    segmentation_to_masks,
)
from xpkg.segmentation.images import (
    best_mask_index,
    masks_from_label_image,
    read_binary_mask,
    read_label_image,
    select_masks_for_save,
    write_binary_mask,
    write_binary_masks,
    write_label_image,
    write_mask_overlay,
)
from xpkg.segmentation.model import (
    ROI,
    MaskType,
    PromptType,
    SegmentationFrame,
    SegmentationMask,
    SegmentationPrompt,
    rasterize_polygon,
)
from xpkg.segmentation.normalized_polygons import (
    NormalizedPolygonLabel,
    read_normalized_polygon_dataset_yaml,
    read_normalized_polygon_labels,
    read_normalized_polygon_rows,
    write_normalized_polygon_dataset_yaml,
    write_normalized_polygon_labels,
    write_normalized_polygon_rows,
)
from xpkg.segmentation.rle import (
    XPKG_RLE_ENCODING,
    XPKG_RLE_ORDER,
    decode_mask_rle,
    encode_mask_rle,
    encode_masks_rle,
    rle_decode,
    rle_encode,
)
from xpkg.segmentation.sam import (
    SamSegmentationResult,
    mask_from_sam_array,
    masks_from_fiesta_result_json,
    masks_from_fiesta_summary,
    masks_from_sam_arrays,
)
from xpkg.segmentation.table import (
    DEFAULT_ROW_GROUP_SIZE,
    MASK_TABLE_KIND,
    MASK_TABLE_SCHEMA_VERSION,
    MaskTableInfo,
    MaskTableInstance,
    MaskTableReader,
    MaskTableRecord,
    MaskTableWriter,
    write_mask_table,
)

__all__ = [
    "DEFAULT_ROW_GROUP_SIZE",
    "MASK_TABLE_KIND",
    "MASK_TABLE_SCHEMA_VERSION",
    "MaskTableInfo",
    "MaskTableInstance",
    "MaskTableReader",
    "MaskTableRecord",
    "MaskTableWriter",
    "XPKG_RLE_ENCODING",
    "XPKG_RLE_ORDER",
    "MaskType",
    "NormalizedPolygonLabel",
    "PromptType",
    "ROI",
    "SamSegmentationResult",
    "SegmentationFrame",
    "SegmentationMask",
    "SegmentationPrompt",
    "annotation_to_masks",
    "annotations_to_masks",
    "best_mask_index",
    "coco_rle_to_mask",
    "decode_mask_rle",
    "encode_mask_rle",
    "encode_masks_rle",
    "mask_from_sam_array",
    "mask_to_coco_annotation",
    "mask_to_coco_polygons",
    "mask_to_coco_rle",
    "masks_from_fiesta_result_json",
    "masks_from_fiesta_summary",
    "masks_from_label_image",
    "masks_from_sam_arrays",
    "rasterize_polygon",
    "read_binary_mask",
    "read_coco_annotations",
    "read_label_image",
    "read_normalized_polygon_dataset_yaml",
    "read_normalized_polygon_labels",
    "read_normalized_polygon_rows",
    "rle_decode",
    "rle_encode",
    "segmentation_to_masks",
    "select_masks_for_save",
    "write_binary_mask",
    "write_binary_masks",
    "write_mask_table",
    "write_label_image",
    "write_mask_overlay",
    "write_normalized_polygon_dataset_yaml",
    "write_normalized_polygon_labels",
    "write_normalized_polygon_rows",
]
