"""Project contract entry points for free-function integrations.

This module defines the free-function form of the project contract: project
creation, import, validation, metadata, segmentation, artifact registry, and
portable ``.expkg`` packing. New integrations should prefer ``ProjectService``
for lifecycle orchestration, while these functions remain public for explicit
function-level callers.
"""

from __future__ import annotations

from xpkg.io.labels.json_format import read_labels_json_payload, write_labels_json
from xpkg.project.artifact import (
    EXPKG_MANIFEST_FILENAME,
    pack_project,
    unpack_project,
    validate_artifact,
    validate_expkg,
    validate_project,
)
from xpkg.project.artifacts import (
    ARTIFACT_INDEX_FILENAME,
    ARTIFACT_MANIFEST_FILENAME,
    ARTIFACT_SCHEMA_VERSION,
    FIGURE_ARTIFACT_SCHEMA_VERSION,
    FIGURE_ARTIFACT_TYPE,
    FIGURE_MANIFEST_FILENAME,
    FIGURES_DIRNAME,
    ArtifactFile,
    ArtifactIndexEntry,
    ArtifactManifest,
    ArtifactOutputSpec,
    FigureArtifact,
    artifact_kind_dir,
    list_project_artifact_index,
    list_project_artifacts,
    list_project_figures,
    load_project_artifact,
    load_project_figure,
    project_artifact_index_path,
    project_artifact_root,
    project_artifact_type_root,
    project_figure_root,
    project_figures_root,
    rebuild_project_artifact_index,
    save_project_artifact,
    save_project_figure,
    validate_project_artifact,
    validate_project_artifacts,
    validate_project_figure,
    validate_project_figures,
)
from xpkg.project.inspection import ProjectInspection, inspect_project
from xpkg.project.layout import (
    ARTIFACTS_DIRNAME,
    EXPKG_SUFFIX,
    PROJECT_DESCRIPTOR_FILENAME,
    ProjectDescriptor,
    default_expkg_path,
    is_project_root,
    load_project_descriptor,
    project_artifacts_root,
    project_descriptor_path,
    project_exports_root,
    project_media_root,
    project_state_root,
    project_store_root,
    resolve_project_root,
    write_project_descriptor,
)
from xpkg.project.metadata import (
    load_project_metadata_field,
    save_project_metadata_field,
)
from xpkg.project.segmentation import (
    SegmentationFrame,
    clear_project_segmentation_masks,
    load_project_segmentation_frames,
    load_project_segmentation_masks,
    save_project_segmentation_masks,
)
from xpkg.project.store import (
    current_project_state_path,
    import_dlc_csv_project,
    import_dlc_h5_project,
    import_dlc_project_directory,
    import_lightning_pose_csv_project,
    import_mediapipe_pose_landmarks_json_project,
    import_mmpose_topdown_json_project,
    import_sleap_h5_project,
    import_sleap_package_project,
    import_vicon_c3d_project,
    import_vicon_csv_project,
    import_vicon_project,
    init_project,
    load_project_metadata,
    load_project_payload,
    load_project_vicon_recording,
    save_project_labels,
    save_project_metadata,
)

__all__ = [
    "ARTIFACTS_DIRNAME",
    "ARTIFACT_INDEX_FILENAME",
    "ARTIFACT_MANIFEST_FILENAME",
    "ARTIFACT_SCHEMA_VERSION",
    "EXPKG_MANIFEST_FILENAME",
    "EXPKG_SUFFIX",
    "FIGURE_ARTIFACT_SCHEMA_VERSION",
    "FIGURE_ARTIFACT_TYPE",
    "FIGURE_MANIFEST_FILENAME",
    "FIGURES_DIRNAME",
    "PROJECT_DESCRIPTOR_FILENAME",
    "ArtifactFile",
    "ArtifactIndexEntry",
    "ArtifactManifest",
    "ArtifactOutputSpec",
    "FigureArtifact",
    "ProjectDescriptor",
    "SegmentationFrame",
    "ProjectInspection",
    "init_project",
    "load_project_descriptor",
    "write_project_descriptor",
    "resolve_project_root",
    "is_project_root",
    "project_descriptor_path",
    "project_exports_root",
    "project_media_root",
    "project_state_root",
    "project_store_root",
    "project_artifacts_root",
    "project_artifact_type_root",
    "project_artifact_root",
    "project_artifact_index_path",
    "project_figures_root",
    "project_figure_root",
    "default_expkg_path",
    "pack_project",
    "unpack_project",
    "validate_project",
    "validate_expkg",
    "validate_artifact",
    "inspect_project",
    "load_project_metadata",
    "load_project_metadata_field",
    "load_project_payload",
    "artifact_kind_dir",
    "list_project_artifacts",
    "list_project_artifact_index",
    "load_project_artifact",
    "save_project_artifact",
    "validate_project_artifact",
    "validate_project_artifacts",
    "rebuild_project_artifact_index",
    "list_project_figures",
    "load_project_figure",
    "save_project_figure",
    "validate_project_figure",
    "validate_project_figures",
    "load_project_segmentation_frames",
    "load_project_segmentation_masks",
    "save_project_labels",
    "save_project_segmentation_masks",
    "clear_project_segmentation_masks",
    "save_project_metadata",
    "save_project_metadata_field",
    "current_project_state_path",
    "load_project_vicon_recording",
    "import_vicon_project",
    "import_vicon_csv_project",
    "import_vicon_c3d_project",
    "import_dlc_csv_project",
    "import_dlc_h5_project",
    "import_dlc_project_directory",
    "import_lightning_pose_csv_project",
    "import_sleap_h5_project",
    "import_sleap_package_project",
    "import_mmpose_topdown_json_project",
    "import_mediapipe_pose_landmarks_json_project",
    "write_labels_json",
    "read_labels_json_payload",
]
