"""Public workspace-first format entry points.

This module defines the stable workspace/project boundary. New integrations
should prefer ``WorkspaceService`` and ``WorkspaceService.imports`` for the
normal lifecycle and ingestion flow, with ``import_*_workspace(...)`` kept
public for explicit function-level callers. The only retained legacy bridge on
this surface is ``migrate_legacy_archive(...)`` for cutting older ``.xpkg``
archives over to the workspace contract.
"""

from __future__ import annotations

from xpkg.formats.project import (
    EXPKG_SUFFIX,
    PROJECT_DESCRIPTOR_FILENAME,
    ProjectDescriptor,
    WorkspaceInspection,
    current_project_snapshot_path,
    current_project_state_path,
    default_expkg_path,
    export_workspace_archive,
    import_detectron2_coco_workspace,
    import_dlc_csv_workspace,
    import_dlc_h5_workspace,
    import_dlc_project_workspace,
    import_mediapipe_pose_landmarks_json_workspace,
    import_mmpose_topdown_json_workspace,
    import_openpose_json_workspace,
    import_sleap_h5_workspace,
    import_sleap_package_workspace,
    import_vicon_c3d_workspace,
    import_vicon_csv_workspace,
    import_vicon_workspace,
    init_project,
    inspect_workspace,
    is_workspace_root,
    load_project_descriptor,
    load_workspace_metadata,
    load_workspace_metadata_field,
    load_workspace_payload,
    load_workspace_vicon_recording,
    migrate_legacy_archive,
    pack_project,
    project_descriptor_path,
    resolve_workspace_root,
    save_workspace_labels,
    save_workspace_metadata,
    save_workspace_metadata_field,
    unpack_project,
    validate_artifact,
    validate_expkg,
    validate_workspace,
    workspace_exports_root,
    workspace_media_root,
    workspace_state_root,
    workspace_store_root,
    write_project_descriptor,
)
from xpkg.io.labels.json_format import read_labels_json_payload, write_labels_json

__all__ = [
    "EXPKG_SUFFIX",
    "PROJECT_DESCRIPTOR_FILENAME",
    "ProjectDescriptor",
    "WorkspaceInspection",
    "init_project",
    "load_project_descriptor",
    "write_project_descriptor",
    "resolve_workspace_root",
    "is_workspace_root",
    "project_descriptor_path",
    "workspace_exports_root",
    "workspace_media_root",
    "workspace_state_root",
    "workspace_store_root",
    "default_expkg_path",
    "export_workspace_archive",
    "pack_project",
    "unpack_project",
    "validate_workspace",
    "validate_expkg",
    "validate_artifact",
    "inspect_workspace",
    "load_workspace_metadata",
    "load_workspace_metadata_field",
    "load_workspace_payload",
    "save_workspace_labels",
    "save_workspace_metadata",
    "save_workspace_metadata_field",
    "current_project_state_path",
    "current_project_snapshot_path",
    "load_workspace_vicon_recording",
    "import_vicon_workspace",
    "import_vicon_csv_workspace",
    "import_vicon_c3d_workspace",
    "import_dlc_csv_workspace",
    "import_dlc_h5_workspace",
    "import_dlc_project_workspace",
    "import_sleap_h5_workspace",
    "import_sleap_package_workspace",
    "import_mmpose_topdown_json_workspace",
    "import_mediapipe_pose_landmarks_json_workspace",
    "import_openpose_json_workspace",
    "import_detectron2_coco_workspace",
    "migrate_legacy_archive",
    "write_labels_json",
    "read_labels_json_payload",
]
