"""Workspace-first project helpers for the public artifact contract.

These free functions stay public for integrations that want an explicit
function-level API. New code should usually drive lifecycle and ingestion
through ``WorkspaceService`` and ``WorkspaceService.imports`` rather than build
around archive-first helpers. Direct archive export stays private to the
workspace storage internals.
"""

from __future__ import annotations

from xpkg.io.project_artifact import (
    pack_project,
    unpack_project,
    validate_artifact,
    validate_expkg,
    validate_workspace,
)
from xpkg.io.project_artifacts import (
    ARTIFACT_INDEX_FILENAME,
    ARTIFACT_MANIFEST_FILENAME,
    ARTIFACT_SCHEMA_VERSION,
    ArtifactFile,
    ArtifactIndexEntry,
    ArtifactManifest,
    ArtifactOutputSpec,
    artifact_kind_dir,
    list_workspace_artifact_index,
    list_workspace_artifacts,
    load_workspace_artifact,
    rebuild_workspace_artifact_index,
    save_workspace_artifact,
    validate_workspace_artifact,
    validate_workspace_artifacts,
    workspace_artifact_index_path,
    workspace_artifact_root,
    workspace_artifact_type_root,
)
from xpkg.io.project_figures import (
    FIGURE_ARTIFACT_SCHEMA_VERSION,
    FIGURE_ARTIFACT_TYPE,
    FIGURE_MANIFEST_FILENAME,
    FIGURES_DIRNAME,
    FigureArtifact,
    list_workspace_figures,
    load_workspace_figure,
    save_workspace_figure,
    validate_workspace_figure,
    validate_workspace_figures,
    workspace_figure_root,
    workspace_figures_root,
)
from xpkg.io.project_inspection import WorkspaceInspection, inspect_workspace
from xpkg.io.project_layout import (
    ARTIFACTS_DIRNAME,
    EXPKG_SUFFIX,
    PROJECT_DESCRIPTOR_FILENAME,
    ProjectDescriptor,
    default_expkg_path,
    is_workspace_root,
    load_project_descriptor,
    project_descriptor_path,
    resolve_workspace_root,
    workspace_artifacts_root,
    workspace_exports_root,
    workspace_media_root,
    workspace_state_root,
    workspace_store_root,
    write_project_descriptor,
)
from xpkg.io.project_metadata import load_workspace_metadata_field, save_workspace_metadata_field
from xpkg.io.project_segmentation import (
    SegmentationFrame,
    clear_workspace_segmentation_masks,
    load_workspace_segmentation_frames,
    load_workspace_segmentation_masks,
    save_workspace_segmentation_masks,
)
from xpkg.io.project_workspace import (
    current_project_snapshot_path,
    current_project_state_path,
    import_detectron2_coco_workspace,
    import_dlc_csv_workspace,
    import_dlc_h5_workspace,
    import_dlc_project_workspace,
    import_mediapipe_pose_landmarks_json_workspace,
    import_mmpose_topdown_json_workspace,
    import_openpose_json_workspace,
    import_sleap_h5_workspace,
    import_sleap_package_workspace,
    import_vicon_c3d_workspace,
    import_vicon_csv_workspace,
    import_vicon_workspace,
    init_project,
    load_workspace_metadata,
    load_workspace_payload,
    load_workspace_vicon_recording,
    migrate_legacy_archive,
    save_workspace_labels,
    save_workspace_metadata,
)

__all__ = [
    "ARTIFACTS_DIRNAME",
    "ARTIFACT_INDEX_FILENAME",
    "ARTIFACT_MANIFEST_FILENAME",
    "ARTIFACT_SCHEMA_VERSION",
    "EXPKG_SUFFIX",
    "FIGURE_ARTIFACT_SCHEMA_VERSION",
    "FIGURE_ARTIFACT_TYPE",
    "FIGURE_MANIFEST_FILENAME",
    "FIGURES_DIRNAME",
    "PROJECT_DESCRIPTOR_FILENAME",
    "ArtifactFile",
    "ArtifactIndexEntry",
    "ArtifactManifest",
    "ArtifactOutputSpec",
    "FigureArtifact",
    "ProjectDescriptor",
    "WorkspaceInspection",
    "init_project",
    "load_project_descriptor",
    "write_project_descriptor",
    "resolve_workspace_root",
    "is_workspace_root",
    "project_descriptor_path",
    "workspace_exports_root",
    "workspace_media_root",
    "workspace_state_root",
    "workspace_store_root",
    "workspace_artifacts_root",
    "workspace_artifact_type_root",
    "workspace_artifact_root",
    "workspace_artifact_index_path",
    "workspace_figures_root",
    "workspace_figure_root",
    "default_expkg_path",
    "pack_project",
    "unpack_project",
    "validate_workspace",
    "validate_expkg",
    "validate_artifact",
    "inspect_workspace",
    "load_workspace_metadata",
    "load_workspace_metadata_field",
    "load_workspace_payload",
    "artifact_kind_dir",
    "list_workspace_artifacts",
    "list_workspace_artifact_index",
    "load_workspace_artifact",
    "save_workspace_artifact",
    "validate_workspace_artifact",
    "validate_workspace_artifacts",
    "rebuild_workspace_artifact_index",
    "list_workspace_figures",
    "load_workspace_figure",
    "save_workspace_figure",
    "validate_workspace_figure",
    "validate_workspace_figures",
    "save_workspace_labels",
    "load_workspace_segmentation_frames",
    "load_workspace_segmentation_masks",
    "save_workspace_segmentation_masks",
    "clear_workspace_segmentation_masks",
    "SegmentationFrame",
    "save_workspace_metadata",
    "save_workspace_metadata_field",
    "current_project_state_path",
    "current_project_snapshot_path",
    "load_workspace_vicon_recording",
    "import_vicon_workspace",
    "import_vicon_csv_workspace",
    "import_vicon_c3d_workspace",
    "import_dlc_csv_workspace",
    "import_dlc_h5_workspace",
    "import_dlc_project_workspace",
    "import_sleap_h5_workspace",
    "import_sleap_package_workspace",
    "import_mmpose_topdown_json_workspace",
    "import_mediapipe_pose_landmarks_json_workspace",
    "import_openpose_json_workspace",
    "import_detectron2_coco_workspace",
    "migrate_legacy_archive",
]
