"""Single public namespace for xpkg format readers.

This is the canonical import location for reader functions and reader-related
data classes. Everything here is re-exported from :mod:`xpkg.io.readers` (the
internal implementation home).

Example:
    >>> from xpkg.readers import read_dlc_csv  # doctest: +SKIP
    >>> from xpkg import readers              # doctest: +SKIP
    >>> readers.read_pose_track(...)          # doctest: +SKIP
"""

from __future__ import annotations

from xpkg.io.readers import (
    KNOWN_BEHAVIOR_SOURCE_TYPES,
    PoseTrack,
    find_first_doric_photometry_file,
    find_first_neurophotometrics_csv,
    find_first_nwb_photometry_file,
    find_first_pyphotometry_csv,
    find_first_pyphotometry_ppd_file,
    find_first_teleopto_h5,
    find_photometry_session_entries,
    is_doric_photometry_file,
    is_neurophotometrics_csv,
    is_nwb_photometry_file,
    is_pyphotometry_csv,
    is_pyphotometry_ppd_file,
    is_rwd_ofrs_session,
    is_tdt_block,
    is_teleopto_h5,
    parse_teleopto_h5_arrays,
    read_anipose_calibration,
    read_behavior_events_csv,
    read_behavior_events_json,
    read_boris_csv,
    read_bsoid_csv,
    read_doric_photometry,
    read_events_csv,
    read_keypoint_moseq_syllables_csv,
    read_neurophotometrics_csv,
    read_nwb_photometry,
    read_opencv_stereo_calibration,
    read_photometry_csv,
    read_pmat_events_csv,
    read_pmat_photometry_csv,
    read_pose_node_names,
    read_pose_track,
    read_pyphotometry_csv,
    read_pyphotometry_ppd,
    read_rwd_ofrs_session,
    read_simba_csv,
    read_tdt_photometry_block,
    read_teleopto_h5,
    resolve_pose_node_indices,
    write_anipose_calibration,
)

__all__ = [
    "PoseTrack",
    "KNOWN_BEHAVIOR_SOURCE_TYPES",
    "find_first_doric_photometry_file",
    "find_first_neurophotometrics_csv",
    "find_first_nwb_photometry_file",
    "find_first_pyphotometry_csv",
    "find_first_pyphotometry_ppd_file",
    "find_first_teleopto_h5",
    "find_photometry_session_entries",
    "is_doric_photometry_file",
    "is_neurophotometrics_csv",
    "is_nwb_photometry_file",
    "is_pyphotometry_csv",
    "is_pyphotometry_ppd_file",
    "is_rwd_ofrs_session",
    "is_tdt_block",
    "is_teleopto_h5",
    "parse_teleopto_h5_arrays",
    "read_anipose_calibration",
    "read_boris_csv",
    "read_bsoid_csv",
    "read_behavior_events_csv",
    "read_behavior_events_json",
    "read_keypoint_moseq_syllables_csv",
    "read_simba_csv",
    "read_doric_photometry",
    "read_events_csv",
    "read_neurophotometrics_csv",
    "read_nwb_photometry",
    "read_opencv_stereo_calibration",
    "read_photometry_csv",
    "read_pmat_events_csv",
    "read_pmat_photometry_csv",
    "read_pose_node_names",
    "read_pose_track",
    "read_pyphotometry_csv",
    "read_pyphotometry_ppd",
    "read_rwd_ofrs_session",
    "read_tdt_photometry_block",
    "read_teleopto_h5",
    "resolve_pose_node_indices",
    "write_anipose_calibration",
]
