"""Generate runtime and typing facades from canonical lazy-export registries."""

from __future__ import annotations

import runpy
import sys
from collections.abc import Mapping
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = (
    ("model", "Canonical in-memory model surface for xpkg.", False),
    ("pose", "Pose primitives, skeletons, and trajectory adapters.", True),
)


def _load_exports(package: str) -> Mapping[str, tuple[str, str]]:
    path = ROOT / f"src/xpkg/{package}/_exports.py"
    exports = runpy.run_path(str(path)).get("EXPORTS")
    if not isinstance(exports, dict):
        raise TypeError(f"EXPORTS must be a dictionary: {path}")
    return exports


def _import_lines(exports: Mapping[str, tuple[str, str]], *, indent: str = "") -> list[str]:
    def sort_key(item: tuple[str, tuple[str, str]]) -> tuple[int, str, int, str]:
        module_name, attribute_name = item[1]
        if attribute_name.isupper():
            name_kind = 0
        elif attribute_name[0].isupper():
            name_kind = 1
        else:
            name_kind = 2
        return int(module_name.startswith(".")), module_name, name_kind, attribute_name.casefold()

    lines: list[str] = []
    relative_group: bool | None = None
    for public_name, (module_name, attribute_name) in sorted(exports.items(), key=sort_key):
        is_relative = module_name.startswith(".")
        if relative_group is not None and is_relative != relative_group:
            lines.append("")
        relative_group = is_relative
        statement = f"from {module_name} import {attribute_name} as {public_name}"
        if len(indent + statement) <= 100:
            lines.append(indent + statement)
        else:
            lines.extend(
                (
                    f"{indent}from {module_name} import (",
                    f"{indent}    {attribute_name} as {public_name},",
                    f"{indent})",
                )
            )
    return lines


def _render_runtime(
    package: str, docstring: str, relative_imports: bool, exports: Mapping[str, tuple[str, str]]
) -> str:
    names = "\n".join(f'    "{name}",' for name in sorted(exports))
    package_arg = ", __name__" if relative_imports else ""
    type_imports = "\n".join(_import_lines(exports, indent="    "))
    return f'''"""{docstring}"""

# Generated by scripts/generate_export_stubs.py. Do not edit.

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from xpkg.{package}._exports import EXPORTS

if TYPE_CHECKING:
{type_imports}

__all__ = [
{names}
]


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {{__name__!r}} has no attribute {{name!r}}") from exc
    module = import_module(module_name{package_arg})
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
'''


def _render_stub(exports: Mapping[str, tuple[str, str]]) -> str:
    lines = ['"""Generated from the adjacent ``_exports.py`` registry."""', ""]
    lines.append("# Generated by scripts/generate_export_stubs.py. Do not edit.\n")
    lines.extend(_import_lines(exports))
    lines.extend(("", "__all__: list[str]", ""))
    return "\n".join(lines)


def main() -> int:
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] not in ([], ["--check"]):
        raise SystemExit("usage: generate_export_stubs.py [--check]")
    stale: list[Path] = []
    for package, docstring, relative_imports in PACKAGES:
        exports = _load_exports(package)
        outputs = {
            ROOT / f"src/xpkg/{package}/__init__.py": _render_runtime(
                package, docstring, relative_imports, exports
            ),
            ROOT / f"src/xpkg/{package}/__init__.pyi": _render_stub(exports),
        }
        for path, expected in outputs.items():
            if check and (not path.is_file() or path.read_text(encoding="utf-8") != expected):
                stale.append(path)
            elif not check:
                path.write_text(expected, encoding="utf-8")
    for path in stale:
        print(f"Stale generated export facade: {path.relative_to(ROOT)}", file=sys.stderr)
    return bool(stale)


if __name__ == "__main__":
    raise SystemExit(main())
