"""Canonical in-memory model surface for xpkg."""

# Generated by scripts/generate_export_stubs.py. Do not edit.

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from xpkg.model._exports import EXPORTS

if TYPE_CHECKING:
    from xpkg.io.labels.model import Labels as Labels
    from xpkg.io.labels.model import SuggestionFrame as SuggestionFrame
    from xpkg.io.skeleton_loaders import load_skeleton as load_skeleton
    from xpkg.io.skeleton_loaders import load_skeleton_dlc as load_skeleton_dlc
    from xpkg.io.skeleton_loaders import load_skeleton_sleap as load_skeleton_sleap
    from xpkg.io.skeleton_loaders import load_skeleton_ultralytics as load_skeleton_ultralytics
    from xpkg.io.skeleton_loaders import load_skeleton_xpkg_json as load_skeleton_xpkg_json
    from xpkg.media.video import Video as Video
    from xpkg.model.behavior import BEHAVIOR_LABELS_SCHEMA_VERSION as BEHAVIOR_LABELS_SCHEMA_VERSION
    from xpkg.model.behavior import BehaviorEmbedding as BehaviorEmbedding
    from xpkg.model.behavior import BehaviorFrameLabel as BehaviorFrameLabel
    from xpkg.model.behavior import BehaviorInterval as BehaviorInterval
    from xpkg.model.behavior import BehaviorLabels as BehaviorLabels
    from xpkg.model.calibration import CALIBRATION_SCHEMA_VERSION as CALIBRATION_SCHEMA_VERSION
    from xpkg.model.calibration import Calibration as Calibration
    from xpkg.model.calibration import CalibrationQuality as CalibrationQuality
    from xpkg.model.calibration import CalibrationSource as CalibrationSource
    from xpkg.model.calibration import Camera as Camera
    from xpkg.model.calibration import CameraDistortion as CameraDistortion
    from xpkg.model.calibration import CameraExtrinsics as CameraExtrinsics
    from xpkg.model.calibration import CameraIntrinsics as CameraIntrinsics
    from xpkg.model.calibration import CameraRotation as CameraRotation
    from xpkg.model.calibration import WorldFrame as WorldFrame
    from xpkg.model.emg import EMGSignalData as EMGSignalData
    from xpkg.model.events import Event as Event
    from xpkg.model.events import EventTable as EventTable
    from xpkg.model.events import SyncEvent as SyncEvent
    from xpkg.model.force import ForcePlateData as ForcePlateData
    from xpkg.model.identity import (
        IDENTITY_PROVENANCE_SCHEMA_VERSION as IDENTITY_PROVENANCE_SCHEMA_VERSION,
    )
    from xpkg.model.identity import IDENTITY_SOURCES as IDENTITY_SOURCES
    from xpkg.model.identity import IdentityConfidenceSpan as IdentityConfidenceSpan
    from xpkg.model.identity import IdentityEvent as IdentityEvent
    from xpkg.model.identity import IdentityProofreadingSpan as IdentityProofreadingSpan
    from xpkg.model.identity import IdentityProvenanceRecord as IdentityProvenanceRecord
    from xpkg.model.metadata import AcquisitionMetadata as AcquisitionMetadata
    from xpkg.model.metadata import CameraMetadata as CameraMetadata
    from xpkg.model.metadata import DatasetShareMetadata as DatasetShareMetadata
    from xpkg.model.metadata import PoseModelProvenance as PoseModelProvenance
    from xpkg.model.reporting import DatasetDatasheet as DatasetDatasheet
    from xpkg.model.reporting import DatasheetCollection as DatasheetCollection
    from xpkg.model.reporting import DatasheetComposition as DatasheetComposition
    from xpkg.model.reporting import DatasheetDistribution as DatasheetDistribution
    from xpkg.model.reporting import DatasheetMaintenance as DatasheetMaintenance
    from xpkg.model.reporting import DatasheetMotivation as DatasheetMotivation
    from xpkg.model.reporting import DatasheetPreprocessing as DatasheetPreprocessing
    from xpkg.model.reporting import DatasheetUses as DatasheetUses
    from xpkg.model.reporting import ModelCard as ModelCard
    from xpkg.model.reporting import ModelCardAnalysis as ModelCardAnalysis
    from xpkg.model.reporting import ModelCardData as ModelCardData
    from xpkg.model.reporting import ModelCardDetails as ModelCardDetails
    from xpkg.model.reporting import ModelCardFactors as ModelCardFactors
    from xpkg.model.reporting import ModelCardIntendedUse as ModelCardIntendedUse
    from xpkg.model.reporting import ModelCardMetrics as ModelCardMetrics
    from xpkg.model.session import RecordingSession as RecordingSession
    from xpkg.model.session import SessionSignal as SessionSignal
    from xpkg.model.session import SessionVideo as SessionVideo
    from xpkg.model.session_actions import (
        InvalidSessionTransitionError as InvalidSessionTransitionError,
    )
    from xpkg.model.session_actions import add_session_signal as add_session_signal
    from xpkg.model.session_actions import add_session_video as add_session_video
    from xpkg.model.session_actions import replace_session_events as replace_session_events
    from xpkg.model.session_actions import replace_session_signal as replace_session_signal
    from xpkg.model.signals import PhotometryChannel as PhotometryChannel
    from xpkg.model.signals import PhotometryRecording as PhotometryRecording
    from xpkg.model.signals import SignalChannel as SignalChannel
    from xpkg.model.signals import TimeSeries as TimeSeries
    from xpkg.model.stubs import VideoStub as VideoStub
    from xpkg.model.stubs import build_prediction_stub as build_prediction_stub
    from xpkg.model.time import Timebase as Timebase
    from xpkg.model.time import Timeline as Timeline
    from xpkg.model.time import TimeRange as TimeRange
    from xpkg.pose.annotations import Instance as Instance
    from xpkg.pose.annotations import KPFlag as KPFlag
    from xpkg.pose.annotations import LabeledFrame as LabeledFrame
    from xpkg.pose.annotations import Point as Point
    from xpkg.pose.annotations import PointArray as PointArray
    from xpkg.pose.annotations import PredictedInstance as PredictedInstance
    from xpkg.pose.annotations import PredictedPoint as PredictedPoint
    from xpkg.pose.annotations import PredictedPointArray as PredictedPointArray
    from xpkg.pose.annotations import Track as Track
    from xpkg.pose.annotations import is_predicted_instance as is_predicted_instance
    from xpkg.pose.skeleton import Keypoint as Keypoint
    from xpkg.pose.skeleton import Skeleton as Skeleton
    from xpkg.pose.skeleton import build_keypoint_skeleton as build_keypoint_skeleton
    from xpkg.pose.trajectory import PoseTrajectory as PoseTrajectory
    from xpkg.segmentation import ROI as ROI
    from xpkg.segmentation import MaskType as MaskType
    from xpkg.segmentation import PromptType as PromptType
    from xpkg.segmentation import SegmentationMask as SegmentationMask
    from xpkg.segmentation import SegmentationPrompt as SegmentationPrompt
    from xpkg.segmentation import rle_decode as rle_decode
    from xpkg.segmentation import rle_encode as rle_encode

__all__ = [
    "AcquisitionMetadata",
    "BEHAVIOR_LABELS_SCHEMA_VERSION",
    "BehaviorEmbedding",
    "BehaviorFrameLabel",
    "BehaviorInterval",
    "BehaviorLabels",
    "CALIBRATION_SCHEMA_VERSION",
    "Calibration",
    "CalibrationQuality",
    "CalibrationSource",
    "Camera",
    "CameraDistortion",
    "CameraExtrinsics",
    "CameraIntrinsics",
    "CameraMetadata",
    "CameraRotation",
    "DatasetDatasheet",
    "DatasetShareMetadata",
    "DatasheetCollection",
    "DatasheetComposition",
    "DatasheetDistribution",
    "DatasheetMaintenance",
    "DatasheetMotivation",
    "DatasheetPreprocessing",
    "DatasheetUses",
    "EMGSignalData",
    "Event",
    "EventTable",
    "ForcePlateData",
    "IDENTITY_PROVENANCE_SCHEMA_VERSION",
    "IDENTITY_SOURCES",
    "IdentityConfidenceSpan",
    "IdentityEvent",
    "IdentityProofreadingSpan",
    "IdentityProvenanceRecord",
    "Instance",
    "InvalidSessionTransitionError",
    "KPFlag",
    "Keypoint",
    "LabeledFrame",
    "Labels",
    "MaskType",
    "ModelCard",
    "ModelCardAnalysis",
    "ModelCardData",
    "ModelCardDetails",
    "ModelCardFactors",
    "ModelCardIntendedUse",
    "ModelCardMetrics",
    "PhotometryChannel",
    "PhotometryRecording",
    "Point",
    "PointArray",
    "PoseModelProvenance",
    "PoseTrajectory",
    "PredictedInstance",
    "PredictedPoint",
    "PredictedPointArray",
    "PromptType",
    "ROI",
    "RecordingSession",
    "SegmentationMask",
    "SegmentationPrompt",
    "SessionSignal",
    "SessionVideo",
    "SignalChannel",
    "Skeleton",
    "SuggestionFrame",
    "SyncEvent",
    "TimeRange",
    "TimeSeries",
    "Timebase",
    "Timeline",
    "Track",
    "Video",
    "VideoStub",
    "WorldFrame",
    "add_session_signal",
    "add_session_video",
    "build_keypoint_skeleton",
    "build_prediction_stub",
    "is_predicted_instance",
    "load_skeleton",
    "load_skeleton_dlc",
    "load_skeleton_sleap",
    "load_skeleton_ultralytics",
    "load_skeleton_xpkg_json",
    "replace_session_events",
    "replace_session_signal",
    "rle_decode",
    "rle_encode",
]


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
