"""Canonical lazy-export registry for :mod:`xpkg.model`."""

from __future__ import annotations

EXPORTS: dict[str, tuple[str, str]] = {
    "AcquisitionMetadata": ("xpkg.model.metadata", "AcquisitionMetadata"),
    "BEHAVIOR_LABELS_SCHEMA_VERSION": (
        "xpkg.model.behavior",
        "BEHAVIOR_LABELS_SCHEMA_VERSION",
    ),
    "BehaviorEmbedding": ("xpkg.model.behavior", "BehaviorEmbedding"),
    "BehaviorFrameLabel": ("xpkg.model.behavior", "BehaviorFrameLabel"),
    "BehaviorInterval": ("xpkg.model.behavior", "BehaviorInterval"),
    "BehaviorLabels": ("xpkg.model.behavior", "BehaviorLabels"),
    "build_keypoint_skeleton": ("xpkg.pose.skeleton", "build_keypoint_skeleton"),
    "CALIBRATION_SCHEMA_VERSION": (
        "xpkg.model.calibration",
        "CALIBRATION_SCHEMA_VERSION",
    ),
    "Calibration": ("xpkg.model.calibration", "Calibration"),
    "CalibrationQuality": ("xpkg.model.calibration", "CalibrationQuality"),
    "CalibrationSource": ("xpkg.model.calibration", "CalibrationSource"),
    "Camera": ("xpkg.model.calibration", "Camera"),
    "CameraDistortion": ("xpkg.model.calibration", "CameraDistortion"),
    "CameraExtrinsics": ("xpkg.model.calibration", "CameraExtrinsics"),
    "CameraIntrinsics": ("xpkg.model.calibration", "CameraIntrinsics"),
    "CameraMetadata": ("xpkg.model.metadata", "CameraMetadata"),
    "CameraRotation": ("xpkg.model.calibration", "CameraRotation"),
    "DatasetDatasheet": ("xpkg.model.reporting", "DatasetDatasheet"),
    "DatasetShareMetadata": ("xpkg.model.metadata", "DatasetShareMetadata"),
    "DatasheetCollection": ("xpkg.model.reporting", "DatasheetCollection"),
    "DatasheetComposition": ("xpkg.model.reporting", "DatasheetComposition"),
    "DatasheetDistribution": ("xpkg.model.reporting", "DatasheetDistribution"),
    "DatasheetMaintenance": ("xpkg.model.reporting", "DatasheetMaintenance"),
    "DatasheetMotivation": ("xpkg.model.reporting", "DatasheetMotivation"),
    "DatasheetPreprocessing": ("xpkg.model.reporting", "DatasheetPreprocessing"),
    "DatasheetUses": ("xpkg.model.reporting", "DatasheetUses"),
    "EMGSignalData": ("xpkg.model.emg", "EMGSignalData"),
    "Event": ("xpkg.model.events", "Event"),
    "EventTable": ("xpkg.model.events", "EventTable"),
    "Experiment": ("xpkg.model.experiment", "Experiment"),
    "ExperimentalCondition": ("xpkg.model.experiment", "ExperimentalCondition"),
    "ExperimentSessionLink": (
        "xpkg.model.experiment",
        "ExperimentSessionLink",
    ),
    "Protocol": ("xpkg.model.experiment", "Protocol"),
    "SessionConditionLink": ("xpkg.model.experiment", "SessionConditionLink"),
    "SessionProtocolLink": ("xpkg.model.experiment", "SessionProtocolLink"),
    "SessionSubjectLink": ("xpkg.model.experiment", "SessionSubjectLink"),
    "Subject": ("xpkg.model.experiment", "Subject"),
    "SubjectTrackLink": ("xpkg.model.experiment", "SubjectTrackLink"),
    "InvalidExperimentTransitionError": (
        "xpkg.model.experiment_actions",
        "InvalidExperimentTransitionError",
    ),
    "add_experiment_session": (
        "xpkg.model.experiment_actions",
        "add_experiment_session",
    ),
    "add_experiment_condition": (
        "xpkg.model.experiment_actions",
        "add_experiment_condition",
    ),
    "add_experiment_protocol": (
        "xpkg.model.experiment_actions",
        "add_experiment_protocol",
    ),
    "add_experiment_subject": (
        "xpkg.model.experiment_actions",
        "add_experiment_subject",
    ),
    "replace_experiment_dataset_share": (
        "xpkg.model.experiment_actions",
        "replace_experiment_dataset_share",
    ),
    "replace_experiment_metadata": (
        "xpkg.model.experiment_actions",
        "replace_experiment_metadata",
    ),
    "replace_experiment_session": (
        "xpkg.model.experiment_actions",
        "replace_experiment_session",
    ),
    "replace_experiment_session_link": (
        "xpkg.model.experiment_actions",
        "replace_experiment_session_link",
    ),
    "ForcePlateData": ("xpkg.model.force", "ForcePlateData"),
    "IDENTITY_PROVENANCE_SCHEMA_VERSION": (
        "xpkg.model.identity",
        "IDENTITY_PROVENANCE_SCHEMA_VERSION",
    ),
    "IDENTITY_SOURCES": ("xpkg.model.identity", "IDENTITY_SOURCES"),
    "Instance": ("xpkg.pose.annotations", "Instance"),
    "IdentityConfidenceSpan": ("xpkg.model.identity", "IdentityConfidenceSpan"),
    "IdentityEvent": ("xpkg.model.identity", "IdentityEvent"),
    "IdentityProofreadingSpan": ("xpkg.model.identity", "IdentityProofreadingSpan"),
    "IdentityProvenanceRecord": ("xpkg.model.identity", "IdentityProvenanceRecord"),
    "is_predicted_instance": ("xpkg.pose.annotations", "is_predicted_instance"),
    "Keypoint": ("xpkg.pose.skeleton", "Keypoint"),
    "KPFlag": ("xpkg.pose.annotations", "KPFlag"),
    "Labels": ("xpkg.io.labels.model", "Labels"),
    "LabeledFrame": ("xpkg.pose.annotations", "LabeledFrame"),
    "load_skeleton": ("xpkg.io.skeleton_loaders", "load_skeleton"),
    "load_skeleton_dlc": ("xpkg.io.skeleton_loaders", "load_skeleton_dlc"),
    "load_skeleton_sleap": ("xpkg.io.skeleton_loaders", "load_skeleton_sleap"),
    "load_skeleton_ultralytics": (
        "xpkg.io.skeleton_loaders",
        "load_skeleton_ultralytics",
    ),
    "load_skeleton_xpkg_json": ("xpkg.io.skeleton_loaders", "load_skeleton_xpkg_json"),
    "MaskType": ("xpkg.segmentation", "MaskType"),
    "ModelCard": ("xpkg.model.reporting", "ModelCard"),
    "ModelCardAnalysis": ("xpkg.model.reporting", "ModelCardAnalysis"),
    "ModelCardData": ("xpkg.model.reporting", "ModelCardData"),
    "ModelCardDetails": ("xpkg.model.reporting", "ModelCardDetails"),
    "ModelCardFactors": ("xpkg.model.reporting", "ModelCardFactors"),
    "ModelCardIntendedUse": ("xpkg.model.reporting", "ModelCardIntendedUse"),
    "ModelCardMetrics": ("xpkg.model.reporting", "ModelCardMetrics"),
    "PhotometryChannel": ("xpkg.model.signals", "PhotometryChannel"),
    "PhotometryRecording": ("xpkg.model.signals", "PhotometryRecording"),
    "Point": ("xpkg.pose.annotations", "Point"),
    "PointArray": ("xpkg.pose.annotations", "PointArray"),
    "PoseModelProvenance": ("xpkg.model.metadata", "PoseModelProvenance"),
    "CoordinateFrameKind": ("xpkg.pose.trajectory", "CoordinateFrameKind"),
    "PoseCoordinateFrame": ("xpkg.pose.trajectory", "PoseCoordinateFrame"),
    "PoseTrajectory": ("xpkg.pose.trajectory", "PoseTrajectory"),
    "PredictedInstance": ("xpkg.pose.annotations", "PredictedInstance"),
    "PredictedPoint": ("xpkg.pose.annotations", "PredictedPoint"),
    "PredictedPointArray": ("xpkg.pose.annotations", "PredictedPointArray"),
    "PromptType": ("xpkg.segmentation", "PromptType"),
    "AlignmentModel": ("xpkg.model.session", "AlignmentModel"),
    "RecordingSession": ("xpkg.model.session", "RecordingSession"),
    "CalibrationCameraLink": ("xpkg.model.session", "CalibrationCameraLink"),
    "SessionBehavior": ("xpkg.model.session", "SessionBehavior"),
    "SessionCalibration": ("xpkg.model.session", "SessionCalibration"),
    "SessionPose": ("xpkg.model.session", "SessionPose"),
    "SessionSignal": ("xpkg.model.session", "SessionSignal"),
    "SessionVideo": ("xpkg.model.session", "SessionVideo"),
    "SynchronizationMethod": ("xpkg.model.session", "SynchronizationMethod"),
    "TimebaseAlignment": ("xpkg.model.session", "TimebaseAlignment"),
    "TimebaseCorrespondence": ("xpkg.model.session", "TimebaseCorrespondence"),
    "InvalidSessionTransitionError": (
        "xpkg.model.session_actions",
        "InvalidSessionTransitionError",
    ),
    "add_session_signal": ("xpkg.model.session_actions", "add_session_signal"),
    "add_session_behavior": ("xpkg.model.session_actions", "add_session_behavior"),
    "add_session_calibration": ("xpkg.model.session_actions", "add_session_calibration"),
    "add_session_pose": ("xpkg.model.session_actions", "add_session_pose"),
    "add_session_video": ("xpkg.model.session_actions", "add_session_video"),
    "add_timebase_alignment": ("xpkg.model.session_actions", "add_timebase_alignment"),
    "fit_timebase_alignment": ("xpkg.model.session_actions", "fit_timebase_alignment"),
    "replace_session_behavior": (
        "xpkg.model.session_actions",
        "replace_session_behavior",
    ),
    "replace_session_acquisition": (
        "xpkg.model.session_actions",
        "replace_session_acquisition",
    ),
    "replace_session_calibration": (
        "xpkg.model.session_actions",
        "replace_session_calibration",
    ),
    "replace_session_events": ("xpkg.model.session_actions", "replace_session_events"),
    "replace_session_metadata": ("xpkg.model.session_actions", "replace_session_metadata"),
    "replace_session_pose": ("xpkg.model.session_actions", "replace_session_pose"),
    "replace_session_signal": ("xpkg.model.session_actions", "replace_session_signal"),
    "replace_session_video": ("xpkg.model.session_actions", "replace_session_video"),
    "replace_timebase_alignment": (
        "xpkg.model.session_actions",
        "replace_timebase_alignment",
    ),
    "ROI": ("xpkg.segmentation", "ROI"),
    "rle_decode": ("xpkg.segmentation", "rle_decode"),
    "rle_encode": ("xpkg.segmentation", "rle_encode"),
    "SegmentationMask": ("xpkg.segmentation", "SegmentationMask"),
    "SegmentationPrompt": ("xpkg.segmentation", "SegmentationPrompt"),
    "SignalChannel": ("xpkg.model.signals", "SignalChannel"),
    "Skeleton": ("xpkg.pose.skeleton", "Skeleton"),
    "SuggestionFrame": ("xpkg.io.labels.model", "SuggestionFrame"),
    "SyncEvent": ("xpkg.model.events", "SyncEvent"),
    "Timebase": ("xpkg.model.time", "Timebase"),
    "Timeline": ("xpkg.model.time", "Timeline"),
    "TimeRange": ("xpkg.model.time", "TimeRange"),
    "TimeSeries": ("xpkg.model.signals", "TimeSeries"),
    "Track": ("xpkg.pose.annotations", "Track"),
    "Video": ("xpkg.media.video", "Video"),
    "VideoStub": ("xpkg.model.stubs", "VideoStub"),
    "WorldFrame": ("xpkg.model.calibration", "WorldFrame"),
    "build_prediction_stub": ("xpkg.model.stubs", "build_prediction_stub"),
}
