"""Pose primitives, skeletons, and trajectory adapters."""

# Generated by scripts/generate_export_stubs.py. Do not edit.

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from xpkg.pose._exports import EXPORTS

if TYPE_CHECKING:
    from xpkg.pose.trajectory import CoordinateFrameKind as CoordinateFrameKind
    from xpkg.pose.trajectory import PoseCoordinateFrame as PoseCoordinateFrame

    from .annotations import Instance as Instance
    from .annotations import KPFlag as KPFlag
    from .annotations import LabeledFrame as LabeledFrame
    from .annotations import Point as Point
    from .annotations import PointArray as PointArray
    from .annotations import PredictedInstance as PredictedInstance
    from .annotations import PredictedPoint as PredictedPoint
    from .annotations import PredictedPointArray as PredictedPointArray
    from .annotations import Track as Track
    from .annotations import is_predicted_instance as is_predicted_instance
    from .skeleton import Keypoint as Keypoint
    from .skeleton import Skeleton as Skeleton
    from .skeleton import build_keypoint_skeleton as build_keypoint_skeleton
    from .trajectory import PoseTrack as PoseTrack
    from .trajectory import PoseTrajectory as PoseTrajectory

__all__ = [
    "CoordinateFrameKind",
    "Instance",
    "KPFlag",
    "Keypoint",
    "LabeledFrame",
    "Point",
    "PointArray",
    "PoseCoordinateFrame",
    "PoseTrack",
    "PoseTrajectory",
    "PredictedInstance",
    "PredictedPoint",
    "PredictedPointArray",
    "Skeleton",
    "Track",
    "build_keypoint_skeleton",
    "is_predicted_instance",
]


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
